---
- name: Deploy index.html on Nginx
  hosts: nginx 

  tasks:
    
    - name: Create Nginx document root directory
      become: true
      file:
        path: /var/www/html
        state: directory
        mode: '0777'

    - name: Copy build/* to Nginx document root
      copy:
        src: /opt/jenkins/workspace/VisOps/t054/sample-nodejs-app/deploy-on-nginx/build/index.html
        dest: /var/www/html/index.html  
        mode: '0777'  

    - name: Restart Nginx service
      become: true  
      service:
        name: nginx
        state: restarted

