---
- name: Build Docker image and run container
  hosts: nginx
  become: yes

  tasks:
    - name: Copy Dockerfile
      copy:
        src: dockerfile
        dest: /home/ubuntu
     
    - name: Copy build file
      copy:
        src: /opt/jenkins/workspace/VisOps/t054/sample-nodejs-app/deploy-on-nginx/build
        dest: /home/ubuntu
        remote_src: false
 

    - name: Build Docker image
      command: docker build -t my-nodejs-image:v1 /home/ubuntu/

    - name: Run Docker container
      command: docker run -it -d -p 8001:3000 my-nodejs-image:v1
